### ISSUE TITLE
package should "recommend" or "suggest" dependencies

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#287]
we don't want hard dependencies since it's not always the right thing to install them on the same host.  But we still want to recommend elasticsearch, cassandra, statsd, and kafka so that people get the memo when they install the package. most packaging systems have some sort of metadata to supply "suggested" package names

**Comment by ctdk** [comment]
I added `--deb-recommends graphite-metrictank` in the https://github.com/raintank/metrictank/tree/docwrk branch, since it's in the same repo as metrictank itself. With those other items, though, I'm not quite sure how to best make the recommendations - not one of those packages comes with debian by default. Do we make a best effort to recommend the correct package even if you have to install a 3rd party repo?

(Also I can't find any way to suggest/recommend packages for rpms using fpm, but I may be missing something there.)

**Comment by ctdk** [comment]
Eh, I've added those packages as `--deb-suggests`. There's not actually a kafka package anywhere that I'm aware of, but it'll point people in the right direction.

**Comment by Dieterbe** [comment]
yeah i think it's ok to suggest package names that don't exist.  they are mostly informational anyway.

but i'm baffled, you're saying none of statsd/elasticsearch/kafka/cassandra is available through standard ubuntu/debian repositories?

**Comment by ctdk** [comment]
Not that I could find. I was pretty surprised too. I went and added them as
deb-suggests anyway even if they aren't in the official repos, but it was
enough to give me pause.

-j
