### ISSUE TITLE
cleanup http api

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#314]
we need to move the HTTP api out of the "main" package and into its own package.

We should also adopt the use of a http framework like macaron or negroni

**Comment by Dieterbe** [comment]
> We should also adopt the use of a http framework like macaron or negroni

why? net/http gives us pretty much everything we need.

I agree that we need to isolate some packages and refactor some things a bit more.
a http package with different handlers in different files seems nice.
I've been thinking about different code organisation patterns. seems a bit tricky since many things reference one another. but the time is right to get cracking on this.
an interesting appproach in this article:
https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1#.bwqibf94u

**Comment by woodsaj** [comment]
> why? net/http gives us pretty much everything we need.

because it makes the code maintainable.

**Comment by Dieterbe** [comment]
how so? what does such a library give us that makes things more maintainable?
the only domain in which I find `net/http` lacking is that the code to validate input parameters can be verbose.  I'm open to using a library that makes this more elegant, but i'm skeptical about the tradeoff of pulling in a dependency for this.

Also for some of the api calls (at least the metrictank-to-metrictank communication) I want to adopt an RPC framework like grpc (which behind the scenes uses http2, but abstracts this away), reducing the need for a http framework.

**Comment by woodsaj** [comment]
> how so? what does such a library give us that makes things more maintainable?
Of course net/http can do everything needed, that is why the webframeworks use it. But we dont need to be re-inventing the wheel.
Issues that a framework fixes:
1) removes the need for doing your own error recovery to prevent panics
2) removes the need for passing way too many arguments to functions, these can be abstracted into a request context or ApiServer struct
3) helpers for form validation
4) better route handling
5) request logging in standard formats
6) future extensiblity that doesn't require refactoring all of the code.

**Comment by Dieterbe** [comment]
1) removes the need for doing your own error recovery to prevent panics

ok. so we could trade in 40 lines of our own by introducing a dependency. fine by me.

2) removes the need for passing way too many arguments to functions, these can be abstracted into a request context or ApiServer struct

we could also implement this with our own struct. should be about 30 lines.

> 3) helpers for form validation

this would be nice to have, and is my main gripe right now.

> 4) better route handling

it would be nice if we could route based on http method, so that the handlers don't have to worry about this anymore. also a slight annoyance I have with net/http here is that we have to register handlers twice if we can expect to be called with or without a trailing slash in the path.

>  5) request logging in standard formats

IMHO logging is a concern that is unrelated to, and should not be tied to a http framework.  we should use the same format and same logger as we use elsewhere in the app.

> 6) future extensiblity that doesn't require refactoring all of the code.

like what?


To conclude, I would consider libraries that provide us with form validation and a solid http router (or muxer which seems to be the same concept) an optionally a recovery handler, there's probably projects focused on just that. I would caution against tieing into a framework or importing large codebases as a dependency, because they also come with a cost

**Comment by Dieterbe** [comment]
done via #378
