### ISSUE TITLE
index op duration confusing

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#349]
https://snapshot.raintank.io/dashboard/snapshot/h4SP9m3pdIlXZIrPdspcllZUDWKB5fdR
this is some index inserts using toxiproxy of +- 1000ms delay
each op takes about a second but for some reason the latencies accumulate over time as shown in lower right graph

**Comment by woodsaj** [comment]
This is because the OP time is measured from the time the metricDef is added to the write queue until it is written.
So latencies are accumulating due to the writes waiting in the writeQueue waiting to be written.

We should probably use 2 timers, one to measure the duration spent in the write queue and one to measure the duration spent writing to cassandra.
