### ISSUE TITLE
Cassandra SSL connection?

### ISSUE THREAD

**Issue by Samaelson** [raintank/metrictank#358]
Is there any implemented option to use metrictank with Cassandra over SSL?

**Comment by Dieterbe** [comment]
There are currently no SSL options exposed. Although MT basically just passes the configured cassandra hosts into https://godoc.org/github.com/gocql/gocql#NewCluster, so you could pass hosts this way that listen for SSL but I guess there's more to the story.

Judging from http://docs.datastax.com/en/cassandra/3.x/cassandra/configuration/secureSSLClientToNode.html and https://github.com/gocql/gocql/pull/251 it looks like we need to expose the SSL options (key, cert, ca path and hostverification, see https://godoc.org/github.com/gocql/gocql#SslOptions) so that you can pass a client cert. interestingly that document mentions a mode to use without client certificates by leaving those options empty.  Is this a way to do SSL also?

I'm not familiar enough with how client<->node SSL should work, or what the various mechanisms are, but hopefully this helps

**Comment by woodsaj** [comment]
metrictank does not currently support SSL.  We would need to add config support for it so we can set the SSLOpts on the gocql.ClusterConfig

https://godoc.org/github.com/gocql/gocql#ClusterConfig

**Comment by Dieterbe** [comment]
fixed by #367
