### ISSUE TITLE
is pickle protocol supported for input ? if so is it documented

### ISSUE THREAD

**Issue by cwolfinger** [raintank/metrictank#391]
Hi - In looking @ the documentation I cannot see if pickle protocol is supported.  It seems like there are pickle vendor code included but no info on whether pickle can be used as an input.  We are trying to use the output from an existing carbon aggregator process to feed the metrictank. My understanding is that carbon aggregator outputs in pickle and metrictank inputs in line format.

**Comment by Dieterbe** [comment]
pickle input is not supported, i just added a clarification to the readme. 
(it's included in vendored code because a library we use to parse storage-schemas.conf imports it)

I think the best solution would be if the official carbon-relay/carbon-aggregator adds support for plaintext output (it doesn't have that? maybe check with the graphite project. maybe that will become available in the upcmonig graphite 1.0), that would make it so much easier for tools in various other languages to be compatible.

implementing pickle input in metrictank could be done, but it would be messy.
you could also check out alternative carbon relays/aggregators, there's a few. https://github.com/graphite-ng/carbon-relay-ng is one of them.
