### ISSUE TITLE
stats versioning

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#396]
current problem: the stats metrics emitted by MT change slightly over time (and will continue to do so for many releases), so dashboards for different MT versions let you select any instance it finds in the metrics tree, which means instances that run different versions and for which the dashboard doesn't work well, or at all.

I see two solutions, both based on encoding the metrictank version in the metric keys.
Note that both share this CON: as you upgrade an instance over time, the older dashboards will still include that instance as long as those old metrics still exist, even though they may not have data for the time range you want to look at. (e.g. was upgraded months ago but you want to look at today)

## solution A: have 1 (or a select few) series encode the metrictank version in the key
we could do this to the series describing the node (primary status etc), this way we can encode the version into the dashboard json, and each dashboard will let you select only the instances that come up with that version. once you select a version, all the other metrics can load as we currently do
PRO:
- metrics namespace doesn't look as "messy"
- if you upgrade a version, you can most likely easily compare metrics before and after upgrade, because most metrics will retain their key and meaning.

CON:
- the metric name space will "clobber" over time. if you want to navigate the tree to create your own dashboards/panels (with a specific version in mind), you may run into a bunch of metrics which are not current anymore, you'll see the same thing in slightly different places (e.g. notifier message size which used to be plugin agnostic but now includes the plugin in the metric path), etc. could be very confusing
- due to the clobbering, the newer dashboards and alerting rules may also be affected by older metrics that accidentally match a new pattern, leading to misleading or downright broken panels and alerts.

## solution B: encode the version into *all* metrics
PRO:
- rules out any clobbering issues

CON:
- metrics tree is a bit more verbose than needed, especially for people who just run 1 version
- every time you introduce a new version there's more work to make sure your alerting rules work, though we can be more explicit in the changelog about changes in metrics. so in most cases we just change the rules to apply to the new version, and otherwise know exactly what change to do.
in practice this problem is the same as if you don't encode the version though, you still need to either assure compatibility or just use `*` to match any version if you're feeling lucky.

**Comment by Dieterbe** [comment]
I think I prefer B, but I need to think about it a bit more.
thoughts @woodsaj ?

**Comment by woodsaj** [comment]
I feel like you are making a simple problem more complicated then it needs to be.

The problem is simply mapping dashboard versions with instances running within the template variables.

1) this seems like a really low priority issue to me.
2) just work around the problem by creating a "links" dashboard.   This dashboard can just use a text panel with html links to other dashboards, passing in the needed tempate variables.

eg
``` 
<a href="/db/metrictank_v0.5.7?var_env=wix&var_instance=wix-tsdb-1">Wix</a>
<a href="/db/metrictank_v0.5.6?var_env=prod&var_instance=all">Prod</a>
```

**Comment by Dieterbe** [comment]
> I feel like you are making a simple problem more complicated then it needs to be.

maybe. on the other hand, since MT is nowhere near finished, its set of emitted metrics will keep changing and we'll keep deploying new versions.  (in the future i also envision running pre-release versions or experimental versions in prod) It's too time consuming to manually maintain instance/env to version mappings, whether in the template variable settings, or in the "links" dashboard (or both. even with the links dashboard i still want the template variable dropdown to make sense)

Also keep in mind it wouldn't be just for us, but for anyone else deploying MT (especially if they do an upgrade) who wants to make sure to have the right dashboard.

it seems to me like the proposed solutions are so trivial I don't see why we wouldn't just do it.
especially B has almost no downside that I can see. do you have a strong objection?

**Comment by woodsaj** [comment]
I definitely have a strong objection to option B. 

including the version in the every metric means that the metric history is lost when you upgrade.  Being able to view how the system has changed after an upgrade is extremely important.  It also makes it impossible to use the same dashboard to view cluster of metrictank instances that are on different versions due to some nodes having been upgraded.

I dont know about you, but I always want the dashboard for a specific metrictank deployment.  I rarely find myself looking at a metrictank dashboard and then just exploring the instances that available in the template variables.  If i want to look at "prod" i shouldn't have to start checking each dashboard version until i find the one that has the prod env.  Niether of these solutions address that problem.

Finally i dont think we should optimize the solution for our unique use case of having numerous clusters all running different versions.  Instead we should optimize for general use case of having a single metrictank cluster that you upgrade.

Though having the version encoded in the metric namespace might seem like it makes things easier now, in the future when the metric namespace reaches stability it will become problematic.

So i am still of the opinion that a single "navigation" dashboard is the best approach for now.  We only have 5 or 6 metrictank deployments that we need track right now.  As this grows we can provide a way to automatically keep the links up to date.

For now, our efforts would be best spent moving us to a position we can keep all deployments of metrictank at the latest version so that this problem doesnt exist.

**Comment by Dieterbe** [comment]
you make some very good points.  FWIW I sometimes find myself browsing around between different environments to compare how different envs/instances do, but i agree with your criticisms.
