### ISSUE TITLE
Support dynamically adding peers

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#436]
when running in k8s as a deployment, it is not possible to determine all peers at startup (as the may not exist yet)

So we need to support adding peers dynamically.  My thoughts for this are a simplified gossip like approach.

node1 starts, has no peers.
node2 starts, knows node1 exists so probes it.  On receiving the probe, node1 now knows that node2 exists.
node3 starts, knows node1 and node2 exist so probes them, notifying them of its existence.

**Comment by Dieterbe** [comment]
> it is not possible to determine all peers at startup (as the may not exist yet)

to clarify, we do support adding peers that don't exist yet.  But the problem here is that the addresses of future peers aren't known in advance.

So with your idea, you basically tell `new` side to poll `old`, and that way `old` becomes aware of `new` as well.

an alternative to your suggestion, is something akin to what ES does (or used to do, haven't caught up): we could just udp probe the entire subnet and add all notes that reply back. we could then have a 'clustername' setting to prevent disparate clusters from joining each other, though I find this approach to be a bit too eager and automagic. I like your idea of being a bit more explicit, more though

**Comment by replay** [comment]
I think ES stopped doing that in some version (that i don't remember) like a year ago. If you want to use their discovery mechanism now you'll need to enable it as a separate module.

**Comment by Dieterbe** [comment]
i believe so yet. at least we could use etcd.
maybe a good way to approach this problem is a pluggable service registry? there could be a plugin to make it config file based, a plugin to use etcd, k8s, etc.

**Comment by replay** [comment]
yeah, that's what i was thinking too. we probably don't want to tie metrictank to k8s, but we can provide selectable discovery methods (like ES)

**Comment by woodsaj** [comment]
I think the best option here is to replace the existing cluster member management with 

https://github.com/hashicorp/memberlist
or
https://github.com/clockworksoul/smudge

With a preference for memberlist due to its maturity.

Both of these libraries are an implementation (with minor changes) of [SWIM](https://www.cs.cornell.edu/~asdas/research/dsn02-swim.pdf)
