### ISSUE TITLE
improve how node ready state is set and handled

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#519]
currently we use a "warmupPeriod" to define when a node should transition from not-ready to ready.
 
What is proposed is that "ready" state should instead be changed to a node priority that is advertised to cluster peers.

If a node is using Kafka input, then the priority is based on the partition lag.
If a node is using Carbon input, then a node should run with low priority until warmupPeriod has elapsed.
If a node is not running in a cluster, then you would want it to just start handling queries as soon as it is online.

All nodes in the cluster would then accept queries as soon as they start up, but when picking the nodes that should be used to handle the query they would use the node priorities to pick the highest priority nodes.

If the cluster is healthy and all nodes have the same priority(high) then the localNode should be preferenced.  
But if the localNode has lower priority then a remote node, the remote node should be used.

**Comment by Dieterbe** [comment]
would it make sense for carbon to set prio to `(warmup-deadline - current time)`, eg the amount of seconds remaining until it's warmed up.  that way if all your nodes are still warming up, it would pick the one that has been up the longest.
it would change the current behavior of ready state though, instead of a cluster unavailable for reads, you would now be more likely to get incomplete reads.

also, both your kafka and carbon suggestion, as well as my carbon suggestion all suffer from a sort of thundering herd problem where a tiny difference in priority (caused by a tiny kafka offset difference or a tiny difference in startup time between carbon MT instances), could cause 1 single instance to be hit for all queries, whereas other instances that have "practically the same but a neglible amount worse priority" are not used for any queries.

so perhaps we should normalize the priorities a bit when taking them into consideration.  E.g. a difference of 10 is negligible, whether talking about kafka offsets or warm up / uptime seconds.

and so when selecting nodes based on their priority, we don't discard them as soon as we find another node with a lower priority, we keep them as long as their priority is not worse by `>10` then the better priority we found.

**Comment by woodsaj** [comment]
The current implementation keeps the existing ready state, which is purely controlled by the warmupPeriod.
The priority is a separate attribute used solely for selecting the peers to use for handling a query.

So, for carbon, nothing changes as all nodes will have the same priority (0).  It would be possible to extend the carbon input plugin later on to set a priority based on uptime but it is not a priority right now.

> so perhaps we should normalize the priorities a bit when taking them into consideration

I thought about this, but it is hard to do so in a way that works for all deployment sizes.  With the current implementation we use the minimum lag for a period that is 10x the offsetCommitInterval (default 5seconds).  But based on the lag numbers in our existing environments this will probably still lead to a large variation in priorities.  

I think the best solution is to dynamically scale the lag based on the input rate, so that it represents a time period.  Ie if the MT instance is consuming at 10k/second and the lag is 10000 then that really means the node is behind by 1second.  But if the rate was only 1k/s with a 10000 lag then it would mean the node is is behind by 10seconds.

**Comment by Dieterbe** [comment]
> I think the best solution is to dynamically scale the lag based on the input rate, so that it represents a time period. Ie if the MT instance is consuming at 10k/second and the lag is 10000 then that really means the node is behind by 1second. But if the rate was only 1k/s with a 10000 lag then it would mean the node is is behind by 10seconds.

hmm this is tricky. if there's an issue consuming, ingest rate will go down and lag will go up. because of the lower ingest rate we would punish extra hard. ideally we would use the ingest rate from when the lag was last stable (e.g. when it was not increasing or decreasing) or potentially when it was last zero, but that could be misleading too if it just processed a huge backlog and had an inflated ingest until it reached 0. perhaps we should look at number of active series.

**Comment by woodsaj** [comment]
I dont thing this will be an issue.  If there is an issue consuming we want to lower the prio of a node.

The ingrest rate is computed based on the number of metrics seen in the last offsetCommitInterval, so there would need to be an issue that lasts longer the 5seconds (or what ever offsetCommitInterval if it is not the default).

**Comment by Dieterbe** [comment]
> if there's an issue consuming, ingest rate will go down and lag will go up. because of the lower ingest rate we would punish extra hard. 

actually this may be a good thing. use current ingest rate to compute "how long would it take at current rate to catch up" (instead of "how much behind are we currently"). the time will be higher, so we punish harder, but that seems like a good thing. (your code does this)

> there would need to be an issue that lasts longer the 5seconds

I don't understand this. think there's a typo here? an issue longer than 5s ?
