### ISSUE TITLE
chuck cache not working as expected

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#544]
with a customer, we were seeing
![cache](https://cloud.githubusercontent.com/assets/20774/23257736/66ed9622-f9c5-11e6-9832-22583d7e5c72.png)

even though we were just refreshing the same dashboard over and over. i would expect 100% hit rate, as cache was also 0.07% used. for now we deployed with an elevated numchunks setting to counteract.

**Comment by replay** [comment]
Do all the requested series actually exist in Cassandra? If you request one that doesn't exist (or doesn't get returned due to cassandra timeout), then the cache doesn't cache the miss. So if you refresh and query the same again there will be another miss again. The graph looks like the ratios are the same on every request, which might indicate this problem

**Comment by Dieterbe** [comment]
#547
