### ISSUE TITLE
Org query to ALL does not work with -1

### ISSUE THREAD

**Issue by tehlers320** [raintank/metrictank#564]
Per the docs "If orgId is -1, returns the metrics for all orgs."

```
curl -H "X-Org-Id: 1" "http://localhost:6060/metrics/find?query=metrictank.*"
[{"allowChildren":1,"expandable":1,"leaf":0,"id":"metrictank.stats","text":"stats","context":{}},{"allowChildren":1,"expandable":1,"leaf":0,"id":"metrictank.usage","text":"usage","context":{}}]
curl -H "X-Org-Id: -1" "http://localhost:6060/metrics/find?query=metrictank.*"
null
```

**Comment by replay** [comment]
Reading the code it seems that the effect of `-1` as `orgId` is rather to only show the public metrics, not all metrics. The docs have been updated the last time at an earlier date than the related code, so the docs might just be outdated on that one.

https://github.com/raintank/metrictank/blame/master/docs/http-api.md#L39
https://github.com/raintank/metrictank/blame/master/idx/memory/memory.go#L255

It should still be possible to implement that feature as the docs currently describe it and make a `-1` that's been passed as parameter result in the metrics of all orgs being returned, but since most of the related code has been rewritten since then it would be pretty much a new feature. So, do you think it's worth it?

**Comment by tehlers320** [comment]
@replay nope, i was just reporting it. We do not have a use case for this and are still unsure if we will even use orgs.

**Comment by Dieterbe** [comment]
That piece of documentation you quoted is from `/metrics/index.json` but you're using the `/metrics/find` api which is different. When I look at the code for index.json it looks correct. I didn't verify it now but I know it used to work.
the find api doesn't have such a facility and I see no reason to add it.  The code you link to @replay just makes sure that whatever org you're under, you also always get to see data in the "public" org -1.
that's how with worldping for example, we expose some timeseries that everyone can see, in addition to their own data.

This why the docs for both index.json and find say "...the given org (or public)" . admittedly the "public" part is a bit vague here and could be clarified, but I don't see an actual bug in the docs or in the code.

**Comment by replay** [comment]
I tested it and can confirm that `-1` on `/metrics/index.json` returns all orgs, so that seems to be working fine as you said @Dieterbe.

**Comment by replay** [comment]
So i guess this can be closed because actually it all works as described, we've just misread the docs.

**Comment by Dieterbe** [comment]
I clarified the docs a bit, but otherwise nothing to do here. Any feedback re docs clarity etc still welcome!

**Comment by replay** [comment]
@Dieterbe the docs are actually really good, I wouldn't know how to further improve them.

**Comment by tehlers320** [comment]
Thanks guys, we just thought we found a problem in the slackchat and jumped to some conclusions. I did not read the api docs thoroughly before diving in to diagnose.
