### ISSUE TITLE
match retention polices based on metric interval

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#579]
currently we support the carbon storage-schemas.conf file for setting retention policy based on regex matches.

This requires knowing the metric namespace in advance and prevents users from changing the interval at which they send data.  both of these issues are big concerns for the hosted-metrics offering.

So to better serve our users we need to be able to apply retention policies based the interval the metrics is being received at.

This will allow us to set a default policy that works for all data users send.
ie
```
[default]
pattern = .*
retentions = 1s:8d:10min:2,1min:5w:2h:2,10min:4month:6h:2,1h:2y:6h:2
retentions = 1min:5w:2h:2,10min:4month:6h:2,1h:2y:6h:2
retentions = 10min:4month:6h:2,1h:2y:6h:2
retentions = 1h:2y:6h:2
```
So if the interval of the metrics is:
- 1h or larger, then we just store raw for 2years
- less then 1h but greater then or equal to 10mins, we store raw for 4months and create 1h rollups
- less then 10min and greater then equal to 1min, we store raw for 5weeks with 10min and 1h rollups
- less then 1min, we store raw for 8days, with 1min, 10min and 1h rollups.

**Comment by replay** [comment]
That's an interesting idea. Does that work for Carbon input as well? When we receive `schema.MetricDefinition` objects it should be no problem to know the interval at which data is coming in, but if the data is coming through carbon we'd have to look at least at two points before we can create the according `AggMetric` for that metric, because before we have the second one we don't know the interval.

**Comment by woodsaj** [comment]
This would not work for carbon, and wouldnt make sense to use it as the schemas file is used to determine what the interval is.  So if you are using carbon, you do know what the interval is all all series in advance.

But supporting direct carbon ingestion is low on the priority list.

**Comment by woodsaj** [comment]
So after thinking about this more, i dont think that we need to pass the multiple retentions in the config.
Instead, we can just remove rollups that have an interval less then interval of the metric when we are generating.

eg, if the schema is 1s:1d,1min:7d  and a metric is received with a resolution of 1min, then we filter 1s:1d from the retention policy.

```
retentions := schema.Retentions
for i, ret := range schema.Retentions
  if ret.SecondsPerPoint >= interval {
     retentions = schema.Retentions[i:]
  }
}
```

I need more time to identify where this should get applied.  I am currently thinking that we find a way to do this in conf/schemas.go. I havent quite worked it all out though.

**Comment by Dieterbe** [comment]
pro : simpler, more reconcilable series (e.g. if a query retrieves a 1s serie and a 1min serie, we don't need runtime consolidation, can just read from the rollup archive)
con: can no longer choose customized rollups based on what raw is: to follow your example, if raw input is 30s, than first rollup of 1min is not very efficient. something like 5min would make more sense, but then potentially we have to reconcile a series of 1m points with one of 5min points and consolidate the 1m to 5m first

Personally I think customly crafted retention schemes based on raw interval make enough sense to make them worthwhile, even though it makes things more complex, both implementation wise, and also when explaining it to users. it's not that common I think that people can't enjoy the intervals that the archive (raw or rollup) provides, because i think people almost always query series that match the same settings pattern.

**Comment by woodsaj** [comment]
> con: can no longer choose customized rollups based on what raw is

this isnt true. You can still set retention policies based on regex matches, ie the traditional graphite/carbon approach.  So if you know in advance the series names you will be using and the interval each is using and you have no plans of changing the interval, then you can just use a normal storage-schemas.conf with all of your retention rules.  

What i am suggesting here is really just to provide way to have a single retention policy that will work for all metrics sent regardless of the interval.  So though efficiency is reduced for some intervals, the gain in simplicity for the user (never having to worry about retention policies) is worth it.

**Comment by Dieterbe** [comment]
>> con: can no longer choose customized rollups based on what raw is
> 
> this isnt true. You can still set retention policies based on regex matches, ie the traditional graphite/carbon approach

Then you require the metrics to have different names. When I said "based on what raw [interval] is", I meant based solely on the interval, i.e. where the metric name remains the same. That's the use case this ticket was opened for: changing the raw interval of a series, while keeping the same name, and without having to modify any configuration files.

If a user wants to exercise this feature ("changing the raw interval of a series, while keeping the same name, and without having to modify any configuration files") then they should be able to also get better rollup archives that correspond to the given raw interval (to avoid cases like 30s raw, 1min rollup for example) which is why I think it's better to define multiple rules to cover all cases with optimal cases

**Comment by woodsaj** [comment]
ok, I get what you are saying. 

But i think the storage efficiency hit is worth it for the simplicity.  Not just the simplicity of having a single retention policy defined in the storage-schemas.conf, but also the simplicity of understanding what data will be stored and for how long.
