### ISSUE TITLE
make per org usage stats work on multinode clusters

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#665]
We currently track numPoints and numSeries per org.  However as these metrics get written directly into the MT instance they dont work on multi node clusters.

Need to change the metrics to be per instance or per shard, so they can then be aggregated at query time.

**Comment by Dieterbe** [comment]
We have to be mindful that "usage tracking for billing" and "usage stats for operational insights" are different things. we don't talk about this difference enough, and it's been creating too much confusion.
they differ because : 
1) MT upgrades, config changes, crash recoveries, etc cause kafka-replays which affect both ingest rate and number of "active" series.  operationally relevant and useful mostly for us (and also somewhat for the customer to the extent they care about these perf stats) but not for billing.
2) replication causes multiplied stats like ingest rate. operationally relevant but not billing relevant.

if the goal is billing stats (both for us and exposing to customer) then I think trying to build it into MT is not the right solution. While we can counteract (2) via proper metrics keying, and even (1) by adding to MT the concept of a seperate offset marker for the purpose of billing, there's still a separation of concerns; I think MT already has enough responsibilities and I think accounting for billing should not be one of them. I think long term that just wouldn't be a good systems design.


Instead I propose these two options: 
1) separate kafka consumers streaming all data solely for the purpose of usage reporting (for billing). this avoids all of the pitfalls above, it shouldn't be any more disk i/o intensive though it would be more network intensive, but if this becomes an issue, we could run these services on the brokers for example.

2) having tsdbgw report usage, keyed by org. we can simply add up the ingest rates for each org across all instances, though for the cardinality measurements to be accurate this requires keys not to move across tsdbgw instances, which has implications both for the customer as well as us

**Comment by woodsaj** [comment]
these stats are not for billing

**Comment by Dieterbe** [comment]
then what are they for exactly? performance insights? if so what kind?

**Comment by woodsaj** [comment]
though the stats are not for billing, we want them to be visible to customers so they can see their usage of the service, so we need to make sure that the numbers make sense.  

Though we can try and sanitise the numbers in MT by only 'recording' stats once nodes have completed replaying any backlog, it is still difficult to get the metrics into MT properly when running in a sharded environment.  We can't just use the existing stats library as that simply reports to a carbon port which won't work for this use case where we want stats to be scoped to a specific org.  So we would have to build our own publisher that can push metrics into MT via tsdb-gw, kafka or some carbon host.

all of that is just far too complicated to be placed in MT and instead, we should just leave the usage accounting up to the ingestion layer before MT, whether that is tsdb-gw, carbon-relay or even Kafka.   For 99% of users who use MT as a single-tenant tsdb, the existing metrics emitted by MT already provide a guage for activeSeries and the rate of metrics can be obtained from kafka, or tsdb-gw or even carbon-relay-ng.


So for achieving our goal of per-org usage stats, we should just extend tsdb-gw to collect them.

**Comment by woodsaj** [comment]
implemented in https://github.com/raintank/tsdb-gw/pull/43
